import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c4c6cf",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#783d01",
        "primary-fixed": "#d5e3ff",
        "on-primary-container": "#879ec6",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-container": "#003b3d",
        "secondary": "#8e4e14",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1a1c1c",
        "on-secondary-fixed-variant": "#6f3800",
        "on-error-container": "#93000a",
        "surface-container-high": "#e8e8e8",
        "background": "#f9f9f9",
        "tertiary-fixed": "#b9ecee",
        "inverse-primary": "#b0c7f1",
        "on-primary-fixed-variant": "#30476a",
        "on-secondary": "#ffffff",
        "surface": "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#b0c7f1",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-container": "#75a5a7",
        "on-surface-variant": "#44474e",
        "surface-container": "#eeeeee",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#2f1400",
        "secondary-fixed-dim": "#ffb780",
        "tertiary-fixed-dim": "#9ecfd1",
        "secondary-container": "#ffab69",
        "primary": "#1D3557",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        "secondary-fixed": "#ffdcc4",
        "error": "#ba1a1a",
        "outline": "#74777f",
        "surface-bright": "#f9f9f9",
        "tertiary": "#002425",
        "inverse-surface": "#2f3131",
        "on-primary-fixed": "#001b3c",
        "on-tertiary-fixed-variant": "#1a4e50",
        "on-surface": "#1a1c1c",
        "primary-container": "#1D3557",
        "surface-tint": "#485f84",
        "on-tertiary-fixed": "#002021",
        "cream": "#F9F7F2",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "Plus Jakarta Sans", "sans-serif"],
        body: ["var(--font-body)", "Inter", "sans-serif"],
        label: ["var(--font-body)", "Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
